language: c

env:
 global:
 - R_BUILD_ARGS="--no-build-vignettes --no-manual --keep-empty-dirs --no-resave-data"
 - R_CHECK_ARGS="--no-vignettes --timings --no-manual"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - chmod 755 ./.install_data.sh
  - chmod 755 ./.push_gh_pages.sh
  - ./travis-tool.sh bootstrap
  - pwd
  - ls

install:
  - ./travis-tool.sh aptget_install r-cran-xml
  - ./travis-tool.sh bioc_install GenomicRanges IRanges hgu133plus2.db BSgenome.Hsapiens.UCSC.hg19
  - ./travis-tool.sh install_r magrittr pracma stats
  - ./travis-tool.sh install_deps
  - ./.install_data.sh

script: 
  - ./travis-tool.sh run_tests

after_success:
  - ./.push_gh_pages.sh

after_failure:
  - ./travis-tool.sh dump_logs


notifications:
  email:
    on_success: change
    on_failure: change